[information]
 name = "dracula"
 background = "dark"
 author = 'Max Miliano'

[palette]
 fg = '#f8f8f2'
 bg = '#282a36'
 float_bg = '#23252f'
 currentline = '#44475a'
 comment = '#6272a4'
 cyan = '#8be9fd'
 green = '#50fa7b'
 orange = '#ffb86c'
 pink = '#ff79c6'
 purple = '#bd93f9'
 red = '#ff5555'
 yellow = '#f1fa8c'
 cursor_fg = '#282a36'
 cursor_bg = '#f8f8f2'
 sign_add = '#50fa7b'
 sign_change = '#ffb866'
 sign_delete = '#ff5555'
 error = '#ff555b'
 warning = '#ffb866'
 info = '#8be9fd'
 hint = '#8be9fd'
 other = '#bd93f9'
 blended_orange = '#483F3E'
 blended_red = '#48303B'
 blended_cyan = '#374754'
 blended_green = '#2E4940'
 blended_purple = '#3E3A53'
 blended_pink = '#5E3E5A'

[highlights]
 Normal = 'fg bg'
 SignColumn = '- bg'
 MsgArea = 'link:Normal'
 ModeMsg = 'fg bg b'
 MsgSeparator = 'fg bg b'
 SpellBad = 'error - u'
 SpellCap = 'info - u'
 SpellLocal = 'warning - u'
 SpellRare = 'other - u'
 NormalNC = 'link:Normal'
 Pmenu = 'link:NormalFloat'
 PmenuSel = '- currentline'
 WildMenu = '- bg b'
 CursorLineNr = 'pink bg'
 Comment = 'comment - i'
 Folded = 'comment currentline'
 FoldColumn = 'fg bg'
 LineNr = 'comment bg'
 FloatBorder = 'comment float_bg'
 Whitespace = 'bg -'
 WinSeparator = 'comment float_bg'
 VertSplit = 'link:WinSeparator'
 CursorLine = '- currentline'
 CursorColumn = 'link:CursorLine'
 ColorColumn = 'link:CursorColumn'
 NormalFloat = 'fg float_bg'
 Visual = '- currentline'
 VisualNOS = 'link:Visual'
 WarningMsg = 'warning bg'
 DiffAdd = 'sign_add - r'
 DiffChange = 'sign_change - r'
 DiffDelete = 'sign_delete - r'
 QuickFixLine = '- currentline b'
 PmenuSbar = 'link:NormalFloat'
 PmenuThumb = '- pink'
 MatchWord = '- - u'
 MatchParen = 'hint bg u'
 MatchWordCur = '- - u'
 MatchParenCur = '- - u'
 Cursor = 'cursor_fg cursor_bg'
 lCursor = 'cursor_fg cursor_bg'
 CursorIM = 'cursor_fg cursor_bg'
 TermCursor = 'cursor_fg cursor_bg'
 TermCursorNC = 'cursor_fg cursor_bg'
 Conceal = 'pink'
 Directory = 'purple'
 SpecialKey = 'purple - b'
 Title = 'cyan - b'
 ErrorMsg = 'error blended_red'
 Search = 'link:Visual'
 IncSearch = 'red blended_red'
 Substitute = 'link:IncSearch'
 MoreMsg = 'cyan - b'
 Question = 'cyan - b'
 EndOfBuffer = 'bg'
 NonText = 'comment'
 Variable = 'fg'
 String = 'yellow'
 Character = 'yellow'
 Constant = 'purple'
 Number = 'purple'
 Boolean = 'purple'
 Float = 'link:Number'
 Identifier = 'green'
 Function = 'link:Identifier'
 Operator = 'pink'
 Type = 'cyan - i'
 StorageClass = 'pink'
 Structure = 'pink'
 Typedef = 'pink'
 Keyword = 'pink'
 Statement = 'pink'
 Conditional = 'pink'
 Repeat = 'pink'
 Label = 'pink'
 Exception = 'pink'
 Include = 'pink'
 PreProc = 'pink'
 Define = 'pink'
 Macro = 'pink'
 PreCondit = 'pink'
 Special = 'pink'
 SpecialChar = 'pink'
 Tag = 'cyan'
 Debug = 'pink'
 Delimiter = 'fg -'
 SpecialComment = 'pink'
 Underlined = '- - u'
 Bold = '- - b'
 Italic = '- - i'
 Ignore = 'purple bg b'
 Todo = 'cyan - b'
 Error = 'error - b'
 TabLine = 'comment bg'
 TabLineSel = 'link:Normal'
 TabLineFill = '- bg'

[TreeSitter]
 '@comment' = 'comment'
 '@comment.documentation' = 'comment'
 '@error' = 'link:Error'
 '@operator' = 'pink'
 '@punctuation.delimiter' = 'fg'
 '@punctuation.delimiter.cpp' = 'pink'
 '@punctuation.delimiter.yaml' = 'pink'
 '@punctuation.bracket' = 'pink'
 '@punctuation.special' = 'pink'
 '@string' = 'yellow'
 '@string.regex' = 'red'
 '@string.escape' = 'pink'
 '@string.special' = 'pink'
 '@character' = 'yellow'
 '@character.special' = 'pink'
 '@function' = 'green'
 '@function.builtin' = 'green'
 '@function.call' = 'green'
 '@method' = 'green'
 '@method.call' = 'green'
 '@constructor' = 'pink'
 '@constructor.c_sharp' = 'link:@type'
 '@constructor.php' = 'link:@type'
 '@parameter' = 'orange - i'
 '@boolean' = 'purple'
 '@number' = 'purple'
 '@float' = 'purple'
 '@label.json' = 'cyan'
 '@label.ruby' = 'link:@variable.builtin'
 '@exception' = 'link:Exception'
 '@type' = 'link:Type'
 '@type.dart' = 'link:@type'
 '@type.builtin' = 'cyan - i'
 '@type.builtin.cpp' = 'pink - i'
 '@type.definition' = 'link:Type'
 '@type.qualifier' = 'pink'
 '@storageclass' = 'pink'
 '@attribute' = 'green - i'
 '@field' = 'fg'
 '@field.yaml' = 'cyan'
 '@property' = 'link:@field'
 '@property.css' = 'cyan'
 '@variable' = 'fg'
 '@variable.builtin' = 'purple - i'
 '@variable.global.ruby' = 'link:@constant'
 '@constant' = 'purple'
 '@constant.builtin' = 'purple'
 '@constant.macro' = 'purple'
 '@namespace' = 'fg'
 '@symbol' = 'purple'
 '@text' = 'yellow'
 '@text.strong' = 'orange - b'
 '@text.emphasis' = 'green - i'
 '@text.strike' = 'yellow - s'
 '@text.title' = 'cyan - b'
 '@text.title.markdown' = 'purple - b'
 '@text.literal' = 'green - i'
 '@text.quote' = 'yellow'
 '@text.uri' = 'cyan'
 '@text.math' = 'pink'
 '@text.reference' = 'pink'
 '@text.todo' = 'link:Todo'
 '@text.warning' = 'link:WarningMsg'
 '@text.danger' = 'link:ErrorMsg'
 '@text.diff.add' = 'link:DiffAdd'
 '@text.diff.delete' = 'link:DiffDelete'
 '@tag' = 'pink'
 '@tag.attribute' = 'green'
 '@tag.delimiter' = 'fg'

[Semantic]
 '@lsp.type.namespace' = 'link:@namespace'
 '@lsp.type.type' = 'link:@type'
 '@lsp.type.typeParameter' = 'link:@type'
 '@lsp.type.class' = 'link:@type'
 '@lsp.type.enum' = 'link:@type'
 '@lsp.type.interface' = 'link:@type'
 '@lsp.type.struct' = 'link:@structure'
 '@lsp.type.parameter' = 'link:@parameter'
 '@lsp.type.variable' = 'link:@variable'
 '@lsp.type.variable.lua' = '- -'
 '@lsp.type.property' = 'link:@property'
 '@lsp.type.enumMember' = 'link:@constant'
 '@lsp.type.function' = 'link:@function'
 '@lsp.type.method' = 'link:@method'
 '@lsp.type.macro' = 'link:@macro'
 '@lsp.type.decorator' = 'link:@function'
 '@lsp.typemod.variable.defaultLibrary' = 'link:@constant'
 '@lsp.typemod.parameter.readyonly' = 'link:Italic'
 '@lsp.typemod.variable.readonly' = 'link:@constant'
 '@lsp.typemod.variable.global' = 'link:@constant'
 '@lsp.typemod.keyword.documentation' = 'link:@keyword'
 '@lsp.typemod.class.documentation' = 'link:@type'
 '@lsp.typemod.property.readonly' = 'link:@constant'  

[Whichkey]
 WhichKey = 'fg'
 WhichKeySeparator = 'pink'
 WhichKeyGroup = 'green'
 WhichKeyDesc = 'cyan'
 WhichKeyFloat = '- float_bg'

[Git]
 SignAdd = 'sign_add'
 SignChange = 'sign_change'
 SignDelete = 'sign_delete'
 GitSignsAdd = 'sign_add'
 GitSignsChange = 'sign_change'
 GitSignsDelete = 'sign_delete'
 GitSignsAddInline = 'green blended_green'
 GitSignsChangeInline = 'orange blended_orange'
 GitSignsDeleteInline = 'red blended_red'

[Illuminate]
 illuminatedWord = '- currentline'
 illuminatedCurWord = 'link:illuminatedWord'
 IlluminatedWordText = 'link:illuminatedWord'
 IlluminatedWordRead = 'link:illuminatedWord'
 IlluminatedWordWrite = 'link:illuminatedWord'

[LSP]
 LspDiagnosticsDefaultError = 'error'
 LspDiagnosticsDefaultWarning = 'warning'
 LspDiagnosticsDefaultInformation = 'info'
 LspDiagnosticsDefaultInfo = 'info'
 LspDiagnosticsDefaultHint = 'hint'
 LspDiagnosticsVirtualTextError = 'error'
 LspDiagnosticsVirtualTextWarning = 'warning'
 LspDiagnosticsVirtualTextInformation = 'info'
 LspDiagnosticsVirtualTextInfo = 'info'
 LspDiagnosticsVirtualTextHint = 'hint'
 LspDiagnosticsFloatingError = 'error'
 LspDiagnosticsFloatingWarning = 'warning'
 LspDiagnosticsFloatingInformation = 'info'
 LspDiagnosticsFloatingInfo = 'info'
 LspDiagnosticsFloatingHint = 'hint'
 DiagnosticHint = 'hint'
 DiagnosticInfo = 'info'
 DiagnosticError = 'error'
 DiagnosticOther = 'other'
 DiagnosticVirtualTextHint = 'hint blended_cyan'
 DiagnosticVirtualTextInfo = 'info blended_cyan'
 DiagnosticVirtualTextWarn = 'warning blended_orange'
 DiagnosticVirtualTextError = 'error blended_red'
 DiagnosticFloatingHint = 'hint'
 DiagnosticFloatingInfo = 'info'
 DiagnosticFloatingWarn = 'warning'
 DiagnosticFloatingError = 'error'
 DiagnosticUnderlineHint = 'hint'
 DiagnosticUnderlineInfo = 'info'
 DiagnosticUnderlineWarn = 'warning'
 DiagnosticUnderlineError = 'error'
 DiagnosticSignError = 'error'
 DiagnosticSignWarning = 'warning'
 DiagnosticSignInformation = 'info'
 DiagnosticSignInfo = 'info'
 DiagnosticSignHint = 'hint'
 DiagnosticSignOther = 'other'
 LspDiagnosticsSignError = 'error'
 LspDiagnosticsSignWarning = 'warning'
 LspDiagnosticsSignInformation = 'info'
 LspDiagnosticsSignInfo = 'info'
 LspDiagnosticsSignHint = 'hint'
 LspDiagnosticsError = 'error'
 LspDiagnosticsWarning = 'warning'
 LspDiagnosticsInformation = 'info'
 LspDiagnosticsInfo = 'info'
 LspDiagnosticsHint = 'hint'
 LspDiagnosticsUnderlineError = '- - u'
 LspDiagnosticsUnderlineWarning = '- - u'
 LspDiagnosticsUnderlineInformation = '- - u'
 LspDiagnosticsUnderlineInfo = '- - u'
 LspDiagnosticsUnderlineHint = '- - u'
 LspReferenceRead = '- float_bg'
 LspReferenceText = '- float_bg'
 LspReferenceWrite = '- float_bg'

[Lspsaga]
 SagaNormal = 'link:NormalFloat'

[Telescope]
 TelescopeTitle = 'cyan - r'
 TelescopeNormal = 'link:NormalFloat'
 TelescopeSelection = 'hint'
 TelescopeMatching = 'info - b'
 TelescopeBorder = 'link:WinSeparator'

[NvimTree]
 NvimTreeRootFolder = 'link:Directory'
 NvimTreeFolderIcon = 'link:Directory'
 NvimTreeIndentMarker = 'link:Directory'
 NvimTreeNormal = 'link:NormalFloat'
 NvimTreeWinSeparator = 'link:WinSeparator'
 NvimTreeVertSplit = 'link:VertSplit'
 NvimTreeFolderName = 'fg'
 NvimTreeOpenedFolderName = 'purple - b'
 NvimTreeEmptyFolderName = 'purple - i'
 NvimTreeGitIgnored = 'comment - i'
 NvimTreeEndOfBuffer = '- float_bg'
 NvimTreeCursorLine = 'link:CursorLine'
 NvimTreeGitStaged = 'sign_add'
 NvimTreeGitNew = 'sign_add'
 NvimTreeGitRenamed = 'sign_add'
 NvimTreeGitDeleted = 'sign_delete'
 NvimTreeGitMerge = 'sign_change'
 NvimTreeGitDirty = 'sign_change'

[NeoTree]
 NeoTreeRootName = 'link:NvimTreeRootFolder'
 NeoTreeDirectoryIcon = 'link:NvimTreeFolderIcon'
 NeoTreeNormal = 'link:NvimTreeNormal'
 NeoTreeNormalNC = 'link:NvimTreeNormalNC'
 NeoTreeWinSeparator = 'link:NvimTreeWinSeparator'
 NeoTreeDirectoryName = 'link:NvimTreeFolderName'
 NeoTreeOpenedDirectoryName = 'link:NvimTreeOpenedFolderName'
 NeoTreeHiddenByName = 'link:NvimTreeEmptyFolderName'
 NeoTreeEndOfBuffer = 'link:NvimTreeEndOfBuffer'
 NeoTreeCursorLine = 'link:NvimTreeCursorLine'
 NeoTreeGitIgnored = 'link:NvimTreeGitIgnored'
 NeoTreeGitAdded = 'link:NvimTreeGitStaged'
 NeoTreeGitConflict = 'link:NvimTreeGitDeleted'
 NeoTreeGitDeleted = 'link:NvimTreeGitDeleted'
 NeoTreeGitModified = 'link:NvimTreeGitDirty'
 NeoTreeGitUnstaged = 'link:NvimTreeGitUnstaged'
 NeoTreeGitUntracked = 'link:NvimTreeGitNew'

[Dap]
 DapUINormal = 'link:NormalFloat'

[StatusLine]
 StatusLine = 'fg float_bg'
 StatusLineNC = 'float_bg float_bg'
 StatusLineSeparator = 'float_bg'
 StatusLineTerm = 'float_bg'
 StatusLineTermNC = 'float_bg'

[Dashboard]
 DashboardHeader = 'red'
 DashboardCenter = 'fg'
 DashboardFooter = 'comment'
 DashboardProjectTitle = 'link:Title'
 DashboardProjectTitleIcon = 'link:Title'
 DashboardProjectIcon = 'purple'
 DashboardMruTitle = 'link:Title'
 DashboardMruIcon = 'link:Title'
 DashboardFiles = 'fg'
 DashboardShotCutIcon = 'cyan'
 DashboardDesc = 'cyan'
 DashboardKey = 'purple'
 DashboardIcon = 'cyan'
 DashboardShotCut = 'purple'

[Cmp]
 CmpItemAbbrDeprecated = 'comment - s'
 CmpItemKindFunction = 'link:@function'
 CmpItemKindMethod = 'link:@method'
 CmpItemKindConstructor = 'link:@constructor'
 CmpItemKindClass = 'link:@storageclass'
 CmpItemKindEnum = 'link:@Constant'
 CmpItemKindInterface = 'link:@type'
 CmpItemKindStruct = 'link:@storageclass'
 CmpItemKindVariable = 'link:@variable'
 CmpItemKindField = 'link:@field'
 CmpItemKindProperty = 'link:@property'
 CmpItemKindEnumMember = 'link:@constant'
 CmpItemKindConstant = 'link:@constant'
 CmpItemKindKeyword = 'link:@keyword'
 CmpItemKindFile = 'fg'
 CmpItemKindFolder = 'cyan'
 CmpItemKindOperator = 'link:@operator'
 CmpItemKindTypeParameter = 'link:@parameter'

[Navic]
 NavicIconsFile = 'fg'
 NavicIconsModule = 'link:@namespace'
 NavicIconsNamespace = 'link:@namespace'
 NavicIconsPackage = 'fg'
 NavicIconsClass = 'link:@type'
 NavicIconsMethod = 'link:@method'
 NavicIconsProperty = 'link:@property'
 NavicIconsField = 'link:@field'
 NavicIconsConstructor = 'link:@constructor'
 NavicIconsEnum = 'link:@type'
 NavicIconsInterface = 'link:@type'
 NavicIconsFunction = 'link:@function'
 NavicIconsVariable = 'link:@variable'
 NavicIconsConstant = 'link:@constant'
 NavicIconsString = 'link:@string'
 NavicIconsNumber = 'link:@number'
 NavicIconsBoolean = 'link:@boolean'
 NavicIconsArray = 'link:@punctuation.bracket'
 NavicIconsObject = 'link:@property'
 NavicIconsKey = 'link:@keyword'
 NavicIconsKeyword = 'link:@keyword'
 NavicIconsNull = 'link:@constant'
 NavicIconsEnumMember = 'link:@type'
 NavicIconsStruct = 'link:@type'
 NavicIconsEvent = 'link:@constant'
 NavicIconsOperator = 'link:@operator'
 NavicIconsTypeParameter = 'link:@parameter'
 NavicText = 'link:@text'

[Notify]
 NotifyBackground = 'link:NormalFloat'
 NotifyERRORBorder = 'error'
 NotifyWARNBorder = 'warning'
 NotifyINFOBorder = 'info'
 NotifyDEBUGBorder = 'comment'
 NotifyTRACEBorder = 'other'
 NotifyERRORIcon = 'error'
 NotifyWARNIcon = 'warning'
 NotifyINFOIcon = 'info'
 NotifyDEBUGIcon = 'comment'
 NotifyTRACEIcon = 'other'
 NotifyERRORTitle = 'error'
 NotifyWARNTitle = 'warning'
 NotifyINFOTitle = 'info'
 NotifyDEBUGTitle = 'comment'
 NotifyTRACETitle = 'other'
 NotifyERRORBody = 'fg bg'
 NotifyWARNBody = 'fg bg'
 NotifyINFOBody = 'fg bg'
 NotifyDEBUGBody = 'fg bg'
 NotifyTRACEBody = 'fg bg'

[Neorg]
 '@neorg.headings.1.title' = 'orange'
 '@neorg.headings.2.title' = 'cyan'
 '@neorg.headings.3.title' = 'green'
 '@neorg.headings.4.title' = 'yellow'
 '@neorg.headings.5.title' = 'red'
 '@neorg.headings.6.title' = 'purple'
 '@neorg.headings.1.prefix' = 'link:@neorg.headings.1.title'
 '@neorg.headings.2.prefix' = 'link:@neorg.headings.2.title'
 '@neorg.headings.3.prefix' = 'link:@neorg.headings.3.title'
 '@neorg.headings.4.prefix' = 'link:@neorg.headings.4.title'
 '@neorg.headings.5.prefix' = 'link:@neorg.headings.5.title'
 '@neorg.headings.6.prefix' = 'link:@neorg.headings.6.title'
 '@neorg.lists.ordered.1.prefix' = 'link:@neorg.headings.1.title'
 '@neorg.lists.ordered.2.prefix' = 'link:@neorg.headings.2.title'
 '@neorg.lists.ordered.3.prefix' = 'link:@neorg.headings.3.title'
 '@neorg.lists.ordered.4.prefix' = 'link:@neorg.headings.4.title'
 '@neorg.lists.ordered.5.prefix' = 'link:@neorg.headings.5.title'
 '@neorg.lists.ordered.6.prefix' = 'link:@neorg.headings.5.title'
 '@neorg.lists.unordered.1.prefix' = 'link:@neorg.lists.ordered.1.prefix'
 '@neorg.lists.unordered.2.prefix' = 'link:@neorg.lists.ordered.2.prefix'
 '@neorg.lists.unordered.3.prefix' = 'link:@neorg.lists.ordered.3.prefix'
 '@neorg.lists.unordered.4.prefix' = 'link:@neorg.lists.ordered.4.prefix'
 '@neorg.lists.unordered.5.prefix' = 'link:@neorg.lists.ordered.5.prefix'
 '@neorg.lists.unordered.6.prefix' = 'link:@neorg.lists.ordered.6.prefix'
 '@neorg.links.file' = 'link:@text.uri'

[IndentBlankLine]
 IndentBlanklineChar = 'blended_purple'
 IndentBlanklineContextChar = 'blended_pink'
 IndentBlanklineSpaceChar = 'purple'
 IndentBlanklineContextSpaceChar = 'pink' 

[Hop]
 HopNextKey = 'pink - b'
 HopNextKey1 = 'cyan - b'
 HopUnmatched = 'comment'
